# YAML
version: '3'
services:
  rtsp:
    image: aler9/rtsp-simple-server
    network_mode: host
    volumes: 
      - ./rtsp-config.yml:/mediamtx.yml
  ivit-i:
    image: maxchanginnodisk/ivit-i-intel:v1.1-runtime
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - /tmp/.x11-unix:/tmp/.x11-unix:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DISPLAY=unix:0